### ISSUE TITLE
Home screen navigation

### ISSUE THREAD

**Issue by jmgasper** [jmgasper/bleconfd#14]
In the Android app, we are changing to support only connecting to `XPI-SETUP`:https://github.com/jmgasper/bleconfd/issues/13

We should replace the current `Home` screen with a screen that checks to ensure that XPI-SETUP is found and can be connected to.  If it can't, we will show a message that states "Please connect your Bluetooth to the XPI-SETUP device".  If there's no connection, we will hide the burger menu so the user can't get to the Wifi and INI screens.

If it is connected, then we will show the new log screen, and the burger menu to get to INI and wifi setup.

**Comment by N1k1tung** [comment]
can we merge Home & Log on android ?

I mean it doesn't seem to show anything now except disconnected status and should be replaced with Log screen when connected

**Comment by jmgasper** [comment]
@N1k1tung - The home screen is just going to be used to show connected state and so we have something to display when there's no connection available.

We're going to add to this in a future challenge as we move towards beaconing.

**Comment by N1k1tung** [comment]
I have a status label showing connection status, or if no devices available showing message about pairing with XPI-SETUP.

Below that are logs.

I can move logs to a separate screen and have only this status message and a logs screen with just logs, but I think it is better to view both status and logs.

Is it fine to keep like that or they MUST be separated?

**Comment by jmgasper** [comment]
It should be separated.

**Comment by N1k1tung** [comment]
ok, then just to be clear should we show any connection-related logs on that screen (when connecting) or just one line for status?

**Comment by jmgasper** [comment]
Just a line for status.

**Comment by jiangliwu** [comment]
@jmgasper according to description, we only need show "Please connect your Bluetooth to the XPI-SETUP device" message when cannot connect to XPI-STEUP.  challenge almost over, i think no need show status label on home page, right?

**Comment by jmgasper** [comment]
The home screen has to show both a successful and unsuccessful connection message.  As long as that's done somewhere, you're fine.

**Comment by jiangliwu** [comment]
when successful, "connect" button will be disabled, "disconnect" button will be enabled, and the message shown in log page

**Comment by seriyvolk83** [comment]
As I understand this ticket is out of scope of iOS challenge, correct?

**Comment by jmgasper** [comment]
@seriyvolk83 - Correct
