### ISSUE TITLE
Log screen

### ISSUE THREAD

**Issue by jmgasper** [jmgasper/bleconfd#15]
Please add a new `Log` tab to the burger menu and corresponding screen.  The log will just show text log information from the Android app about the bluetooth connection and relevant calls sent to the bleconfd server and responses received.  Anything pertinent that we can add here that will help with debugging will help in the future.

**Comment by N1k1tung** [comment]
should we also keep text logs on file system (and make them accessible via itunes file sharing)?
otherwise it won't be very useful

**Comment by jmgasper** [comment]
Not required, but that would be fine.
