### ISSUE TITLE
iOS app build

### ISSUE THREAD

**Issue by jmgasper** [jmgasper/bleconfd#18]
We currently have an Android app that can:

* Connect to the rPi 3 B+, running bleconfd over BLE
* Send Wifi connection details and initiate the connection process on the rPi
* Get, update, and delete Glib INI file details from the client phone / device to the rPi server

We want to build out an iOS app that can do the exact same thing.  This challenge will build the iOS app.

### Updates

Note that we are updating the code in parallel with this challenge.  We will *not* consider these changes in this challenge:

* https://github.com/jmgasper/bleconfd/issues/10
* https://github.com/jmgasper/bleconfd/issues/13
* https://github.com/jmgasper/bleconfd/issues/14

We can continue to have functionality like what exists in the Android app now (hash 30ec664).  Please expect the bleconfd server to run the code in hash 30ec664.

A video of the Android app running can be found here:
https://www.dropbox.com/s/db47815cxc45unt/device-2018-12-14-122735.mp4?dl=1

And descriptions of the functionality in the closed tickets can be found here

* https://github.com/jmgasper/bleconfd/issues/3
* https://github.com/jmgasper/bleconfd/issues/9 -- This one's important.  Make sure that the iOS implementation offers the same functionality.

## UI

The UI can be as standard as possible.  There should be a side menu that has options for:

* Log
* Wifi Setup
* INI file

### Log

See the log screen requirements here:  https://github.com/jmgasper/bleconfd/issues/15

We want to make sure we capture any relevant debug information about connection, messages, errors etc... on this screen

### Wifi setup

As noted in issue #3 , the wifi setup screen will take an SSID and a WPA2 key and will send that to the rPi to initiate a connection.  This information should be passed the same way as it is in the current Android app.

As on Android, if we can pre-populate the SSID (if the iOS device is on wifi), that would be helpful:

https://github.com/jmgasper/bleconfd/issues/12

### Glib INI file editing

As noted in issue #9, the iOS app must allow for viewing and updating a Glib ini file through the app.  Groups and key / value pairs will be maintainable.

Note that the UI should be relatively easy to use.  Please allow for the functionality changes described here https://github.com/jmgasper/bleconfd/issues/11

## Target

Please target the latest version of XCode.  I am fine targeting a relatively recent version of iOS as well - iOS 10 or 11 would be fine.  We will use the latest version of Swift as the programming language.

## CocoaPods

If you'd like to use 3rd party libraries to help with either the UI or BLE functionality, that's fine, but please ensure they are BSD or MIT licensed.  CocoaPods can be used to import 3rd party libs.

If you are unsure if a library will be allowed, feel free to just ask in the forum.

**Comment by N1k1tung** [comment]
can we target abb1aa833cb0f0259070acf96c4b5a34a70854f2 instead (the commit only restored android app)?

**Comment by N1k1tung** [comment]
are Apache-2.0 libraries allowed to use?

**Comment by jmgasper** [comment]
Targeting commit abb1aa8 is fine.  I'm checking on Apache licensing.

**Comment by N1k1tung** [comment]
Apache-2.0 is basically same as MIT when used as a library (no code modifications to document and we don't use their name as trademark - those are the only differences between the licenses)

edit: bleconfd is under Apache-2.0 as well

**Comment by jmgasper** [comment]
We're still working on this.  For now, it's fine for the challenge, since we likely won't get clarification anytime soon.

**Comment by seriyvolk83** [comment]
Can we use "Wifi Settings" label (as in Android) instead of "Wifi Setup"?

**Comment by jmgasper** [comment]
Sure
